### ISSUE TITLE
GitHub Actions で json ファイルを自動更新する

### ISSUE THREAD

**Issue by torippy1024** [hiroto-toriyama/connpass-api#1]
一定時間おきにGitHub Actionsが実行されるようにする。
Pythonでその時のデータを取得し、jsonファイルに出力、
その後gh-pagesブランチにpublishする。

**Comment by torippy1024** [comment]
15分ごとに実行されるようcron設定したが、実行開始時間にばらつきがある。
その上gh-pagesブランチにpublishできてない。

**Comment by hiroto-toriyama** [comment]
e7d1c9

**Comment by hiroto-toriyama** [comment]
e7d1c99b77d89d369621821f26162d2f256cfeec

**Comment by torippy1024** [comment]
[cronの設定を変更](https://github.com/hiroto-toriyama/connpass-api/commit/e7d1c99b77d89d369621821f26162d2f256cfeec)https://github.com/hiroto-toriyama/connpass-api/commit/e7d1c99b77d89d369621821f26162d2f256cfeec

**Comment by torippy1024** [comment]
Actionsのログを確認すると、0:00を過ぎてるにも関わらず昨日の日付でAPIを叩いている。
9:00過ぎのActionsを確認すると、今日の日付でAPIを叩いており、gh-pagesへのpublishがされていた。
このことからタイムゾーンの問題であると考えられる。

解決策として
* Actionsでタイムゾーンを設定する
* Pyhton側でタイムゾーンを設定する

の2つが考えられるが、Python単体で動作が保証されるべきであるため後者で対応する。

**Comment by hiroto-toriyama** [comment]
26b8de2b09d2eb06d3711d9106dd80a9730cfb5f

**Comment by torippy1024** [comment]
[タイムゾーンを日本に](https://github.com/hiroto-toriyama/connpass-api/commit/26b8de2b09d2eb06d3711d9106dd80a9730cfb5f)https://github.com/hiroto-toriyama/connpass-api/commit/26b8de2b09d2eb06d3711d9106dd80a9730cfb5f

**Comment by torippy1024** [comment]
0:00を跨ぐと狙い通りAPIが変わっていることを確認。
これで1時間ごとにデータの更新が行われるようになった。

[GitHub Actions のスケジュール実行はスケジュール通りには動いてくれないようだ - Qiita](https://qiita.com/tommy_aka_jps/items/5f4fe384008ffc9fa794)
実行開始時間にばらつきがあるのは GitHub Actions の仕様のようだ。
最悪一日一回実行されればいいためそこまで問題ないが、
0:00~1:00あたりのデータは昨日のデータである可能性があることを留意。

[スケジュール実行のワークフローはリポジトリを60日放置すると動かなくなる - Qiita](https://qiita.com/tommy_aka_jps/items/65193185b520a1e2be21)
しばらく先だが注意しておく。
